#include "types.h"

#ifndef IHMMANAGEMENT_H
#define IHMMANAGEMENT_H

typedef enum {VEILLE,VEILLE_ACTION,NOUVELLE_TOUCHE,NOUVELLE_TOUCHE_ACTION,SAISI_EN_COURS,SAISI_EN_COURS_ACTION,MAUVAIS_CODE,MAUVAIS_CODE_ACTION,ATTENTE,ATTENTE_ACTION,COMMANDE_ACTIVE,COMMANDE_ACTIVE_ACTION,ENREGISTRE,ENREGISTRE_ACTION,ENREGISTRE_SUCCES,ENREGISTRE_SUCCES_ACTION} EtatIHM_T;

void IHMManagementPeriod (EtatIHM_T EtatIHMWanted);

#endif

